name: markdown_io
description: A toolbox for creating markdown editable fields, widgets and displays
version: 0.0.1-dev.1
homepage: https://github.com/Meghatronics/flutter-markdown-io
repository: https://github.com/Meghatronics/flutter-markdown-io

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.5

dev_dependencies:
  effective_dart: ^1.3.1
  flutter_test:
    sdk: flutter

flutter: null
